export const DESKTOP_MIN_WINDOW_WIDTH = 680;
export const DESKTOP_MIN_WINDOW_HEIGHT = 420;
export const DESKTOP_PLAYER_HEIGHT = 104;
export const DESKTOP_COMPACT_PLAYER_HEIGHT = 120;
export const DESKTOP_SIDEBAR_EXPANDED_WIDTH = 240;
export const DESKTOP_SIDEBAR_COLLAPSED_WIDTH = 72;
export const DESKTOP_SIDEBAR_AUTO_COLLAPSE_WIDTH = 1080;
export const DESKTOP_QUEUE_PANEL_WIDTH = 160;
