import {
  DESKTOP_WHEEL_STEP_PERCENT,
  MAX_VOLUME_PERCENT,
  NORMAL_ZONE_RATIO,
} from '@ton/core';

export const MAX_VOLUME = MAX_VOLUME_PERCENT;
export const NORMAL_ZONE = NORMAL_ZONE_RATIO;
export const WHEEL_STEP = DESKTOP_WHEEL_STEP_PERCENT;
