from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ANDROID_DIR = REPO_ROOT / "packages" / "mobile" / "android"
ANDROID_APP_BUILD_GRADLE = ANDROID_DIR / "app" / "build.gradle"
ANDROID_KEYSTORE = ANDROID_DIR / "app" / "release.keystore"
ANDROID_KEYSTORE_PROPERTIES = ANDROID_DIR / "keystore.properties"
LOCAL_SIGNING_DIR = REPO_ROOT / ".signing" / "android"
LOCAL_KEYSTORE = LOCAL_SIGNING_DIR / "ton-release.keystore"
LOCAL_KEYSTORE_PROPERTIES = LOCAL_SIGNING_DIR / "keystore.properties"
EXPECTED_CERTIFICATE_SHA256 = REPO_ROOT / "scripts" / "android-release-cert.sha256"

ANDROID_KEYSTORE_BASE64_ENV = "TON_ANDROID_KEYSTORE_BASE64"
ANDROID_KEYSTORE_PASSWORD_ENV = "TON_ANDROID_KEYSTORE_PASSWORD"
ANDROID_KEY_ALIAS_ENV = "TON_ANDROID_KEY_ALIAS"
ANDROID_KEY_PASSWORD_ENV = "TON_ANDROID_KEY_PASSWORD"
