export {
  areEqBandsEqual,
  CANONICAL_EQ_FREQUENCIES,
  DEFAULT_EQ_BANDS,
  ensureAudioEffectsAttached,
  getAudioSettingsSupportSnapshot,
  getEqFrequencyLabel,
  getEqInfo,
  inferEqPresetName,
  initializeEqualizer,
  mapPresetToBands,
  normalizeEqGain,
  restoreAudioSettings,
  setEqBand,
  setEqPresetByName,
  setFrequency,
  setLoudnessNormalizationEnabled,
  supportsEqualizerEffects,
  supportsLoudnessAnalysis,
  supportsLoudnessBoost,
  supportsPitchAdjustment,
  toggleEq,
  toggleLoudnessNormalization,
} from './audio-settings/index';
