/**
 * PO Token (Proof of Origin) generator for YouTube streaming.
 *
 * YouTube requires a po_token generated by BotGuard to serve streaming URLs.
 * Since BotGuard needs a real browser environment (DOM, new Function(), etc.),
 * we run the entire flow inside our hidden WebView.
 *
 * Flow:
 * 1. RN side generates visitorData via youtubei.js protobuf encoding
 * 2. RN injects a JS command into the WebView to generate po_token
 * 3. WebView fetches BotGuard challenge from Google API
 * 4. WebView loads & runs BotGuard interpreter JS
 * 5. WebView mints po_token using visitorData as identifier
 * 6. WebView posts {poToken, visitorData} back to RN
 * 7. RN caches result and passes to Innertube.create()
 */

import type WebView from 'react-native-webview';

export type PoTokenBinding = 'session' | 'video';

export interface PoTokenResult {
  binding: PoTokenBinding;
  poToken: string;
  visitorData: string;
  expiresAt: number;
  videoId?: string;
}

export interface GetPoTokenOptions {
  binding?: PoTokenBinding;
  videoId?: string;
  visitorData?: string;
}

let webViewRef: WebView | null = null;
let cachedSessionResult: PoTokenResult | null = null;
let lastVisitorData: string | null = null;
let pendingSessionGeneration: Promise<PoTokenResult> | null = null;
const pendingVideoGenerations = new Map<string, Promise<PoTokenResult>>();

const TOKEN_TTL_MS = 6 * 3600 * 1000; // 6 hours default, refresh before expiry

type PendingResolve = {
  resolve: (result: PoTokenResult) => void;
  reject: (error: Error) => void;
};

const pendingRequests = new Map<string, PendingResolve>();
let requestId = 0;

export function registerPoTokenWebView(ref: WebView | null) {
  webViewRef = ref;
}

export function handlePoTokenMessage(data: string): boolean {
  try {
    const msg = JSON.parse(data);
    if (msg.type === 'po_token_log') {
      console.log('[PO-TOKEN-WV]', msg.msg);
      return true;
    }
    if (msg.type !== 'po_token_result' && msg.type !== 'po_token_error') {
      return false;
    }
    const pending = pendingRequests.get(msg.id);
    if (!pending) return true;
    pendingRequests.delete(msg.id);

    if (msg.type === 'po_token_error') {
      pending.reject(new Error(msg.error));
    } else {
      const result = {
        binding: msg.binding === 'video' ? 'video' : 'session',
        poToken: msg.poToken,
        videoId: typeof msg.videoId === 'string' ? msg.videoId : undefined,
        visitorData: msg.visitorData,
        expiresAt: Date.now() + (msg.ttlSecs ? msg.ttlSecs * 1000 : TOKEN_TTL_MS),
      } satisfies PoTokenResult;
      lastVisitorData = result.visitorData;
      pending.resolve(result);
    }
    return true;
  } catch {
    return false;
  }
}

/**
 * Get a valid po_token + visitorData pair.
 *
 * Session-bound tokens are cached until shortly before expiry. Video-bound
 * tokens are generated per video because YouTube can bind them to video IDs.
 */
export async function getPoToken(
  options: GetPoTokenOptions | string = {},
): Promise<PoTokenResult> {
  const normalizedOptions: GetPoTokenOptions = typeof options === 'string'
    ? { binding: 'session', visitorData: options }
    : options;
  const binding = normalizedOptions.binding ?? 'session';

  if (binding === 'video') {
    const videoId = normalizedOptions.videoId?.trim();
    if (!videoId) {
      throw new Error('videoId is required for video-bound po_token');
    }

    const pendingVideoGeneration = pendingVideoGenerations.get(videoId);
    if (pendingVideoGeneration) {
      return pendingVideoGeneration;
    }

    const visitorData = normalizedOptions.visitorData
      ?? cachedSessionResult?.visitorData
      ?? lastVisitorData
      ?? undefined;
    const pending = generatePoToken({
      binding: 'video',
      identifier: videoId,
      videoId,
      visitorData,
    }).finally(() => {
      pendingVideoGenerations.delete(videoId);
    });
    pendingVideoGenerations.set(videoId, pending);
    return pending;
  }

  if (cachedSessionResult && cachedSessionResult.expiresAt > Date.now() + 60000) {
    return cachedSessionResult;
  }

  if (pendingSessionGeneration) {
    return pendingSessionGeneration;
  }

  pendingSessionGeneration = generatePoToken({
    binding: 'session',
    visitorData: normalizedOptions.visitorData,
  }).finally(() => {
    pendingSessionGeneration = null;
  });

  const result = await pendingSessionGeneration;
  cachedSessionResult = result;
  lastVisitorData = result.visitorData;
  return result;
}

/**
 * Check if the po_token system is ready (WebView registered).
 */
export function isPoTokenReady(): boolean {
  return webViewRef !== null;
}

/**
 * Force refresh the cached po_token.
 */
export function invalidatePoToken(options: { binding?: PoTokenBinding; videoId?: string } = {}) {
  const binding = options.binding;
  if (!binding || binding === 'session') {
    cachedSessionResult = null;
    pendingSessionGeneration = null;
    webViewRef?.injectJavaScript(`
      if (window.__resetPoTokenGenerator) window.__resetPoTokenGenerator();
      true;
    `);
  }

  if (!binding || binding === 'video') {
    if (options.videoId) {
      pendingVideoGenerations.delete(options.videoId);
    } else {
      pendingVideoGenerations.clear();
    }
  }
}

async function generatePoToken(options: {
  binding: PoTokenBinding;
  identifier?: string;
  videoId?: string;
  visitorData?: string;
}): Promise<PoTokenResult> {
  if (!webViewRef) {
    throw new Error('WebView not ready for po_token generation');
  }

  const id = `pot_${++requestId}`;

  return new Promise<PoTokenResult>((resolve, reject) => {
    pendingRequests.set(id, { resolve, reject });

    const script = `
(function() {
  window.__generatePoToken(
    ${JSON.stringify(id)},
    ${JSON.stringify(options.visitorData || '')},
    ${JSON.stringify(options.identifier || '')},
    ${JSON.stringify(options.binding)},
    ${JSON.stringify(options.videoId || '')}
  );
})();
true;`;

    webViewRef!.injectJavaScript(script);

    setTimeout(() => {
      if (pendingRequests.has(id)) {
        pendingRequests.delete(id);
        reject(new Error('po_token generation timed out after 30s'));
      }
    }, 30000);
  });
}
